##Pair numbers:

## it is wrong to divide by all the numbers. it should normalize by total unambiguous sites+invariable sites.
## total sites-total non-conserved sites + total unambiguous sites from oltype.Rout generated by sankoff-v#.R
ol0.pairnum=33
ol3.pairnum=665
ol5.pairnum=18
nol.pairnum=1144
emda.pairnum=129
emdp.pairnum=71

nodes=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")

ol3=read.table("ol3-events.txt",header=T)
colnames(ol3)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
ol3=as.matrix(ol3)/ol3.pairnum

ol5=read.table("ol5-events.txt",header=T)
colnames(ol5)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
ol5=as.matrix(ol5)/ol5.pairnum

ol0=read.table("ol0-events.txt",header=T)
colnames(ol0)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
ol0=as.matrix(ol0)/ol0.pairnum


emda=read.table("emda-events.txt",header=T)
colnames(emda)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
emda=as.matrix(emda)/emda.pairnum


emdp=read.table("emdp-events.txt",header=T)
colnames(emdp)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
emdp=as.matrix(emdp)/emdp.pairnum


nol=read.table("nol-events.txt",header=T)
colnames(nol)=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
nol=as.matrix(nol)/nol.pairnum

## normalize??
## normalize.factor=colSums(nol)
## for (i in 1:20){ol3[,i]=ol3[,i]/normalize.factor[i]}
## for (i in 1:20){ol5[,i]=ol5[,i]/normalize.factor[i]}
## for (i in 1:20){ol0[,i]=ol0[,i]/normalize.factor[i]}
## for (i in 1:20){emda[,i]=emda[,i]/normalize.factor[i]}
## for (i in 1:20){emdp[,i]=emdp[,i]/normalize.factor[i]}

## print-out by ol type
## par(mfrow=c(2,3))
## barplot(ol3,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## barplot(ol5,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## barplot(ol0,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## barplot(emda,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## barplot(emdp,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## barplot(nol,col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1)
## legend("topright", c("gainloss.in", "rearrange.in", "gainloss.out", "rearrange.out"), col=c("red","blue","green","yellow"),pch=rep(15,5),cex=0.8,bty="n")

## need to fix error bar problem->need to calcualte sd in sankoff1-v1.R
## error.bar <- function(x, y, upper, lower=upper, length=0.02){
## if(length(x) != length(y) | length(y) !=length(lower) | length(lower) != length(upper))
## stop("vectors must be same length")
## arrows(x,y+upper, x, y-lower, angle=90, code=3, length=0.02)
## }
## for i in (1:22){
##    i=18
##    sum=colSums(cbind(nol[,i],emdp[,i],emda[,i],ol5[,i],ol0[,i],ol3[,i]))
##    nol.error=sqrt(sum[1]*(1-sum[1])/nol.pairnum)
##    emdp.error=sqrt(sum[2]*(1-sum[2])/emdp.pairnum)
##    emda.error=sqrt(sum[3]*(1-sum[3])/emda.pairnum)
##    ol5.error=sqrt(sum[4]*(1-sum[4])/ol5.pairnum)
##    ol0.error=sqrt(sum[5]*(1-sum[5])/ol0.pairnum)
##    ol3.error=sqrt(sum[6]*(1-sum[6])/ol3.pairnum)

##    error=c(nol.error,emdp.error,emda.error,ol5.error,ol0.error,ol3.error)
   
##    total.bar=barplot(cbind(nol[,i],emdp[,i],emda[,i],ol5[,i],ol0[,i],ol3[,i]),
##               col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1,xlim=c(0,0.15))
##    error.bar(total.bar,sum, 1.96*error)
##  }


##print-out by branch

for (i in 1:20){
file=paste(nodes[i],".svg",sep="")
        svg(file,width=7,height=3)
barplot(cbind(nol[,i],emdp[,i],emda[,i],ol5[,i],ol0[,i],ol3[,i]),
              col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1,xlim=c(0,0.10))
dev.off()
}

## ##print-out by branch-normalized version
## nodes=c("18.16","18.12","22.21","22.9","21.15","21.20","20.19","20.6","19.14","19.17","17.13","17.1","13.2","13.3","14.4","14.5","15.7","15.8","16.10","16.11")
## for (i in 1:20){
##   file=paste(nodes[i],".svg",sep="")
##   svg(file,width=7,height=3)
##   barplot(cbind(emdp[,i],emda[,i],ol5[,i],ol0[,i],ol3[,i]),
##           col=c("red","blue","green","yellow"),horiz=T,cex.axis=0.8,las=1,xlim=c(0,3))
##   dev.off()
## }
